#!/usr/bin/env bash
# a script to install nginx on a server

sudo apt update && sudo apt install -y nginx

# rewriting content of default nginx page
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# reload nginx configuration
sudo service nginx start
