#!/usr/bin/env bash
# installing haproxy and setting up load balancing

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get install -y haproxy=2.8.\*

haproxy_config="\nfrontend haproxynode\n
\tbind *:80
\tmode http
\tdefault_backend web_servers

backend web_servers\n
\tbalance roundrobin
\tserver 251659-web-01 18.206.202.36
\tserver 251659-web-02 100.25.199.205
"

echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
