#!/usr/bin/env bash
# a bash script that creates a file with its own PID

filename="/var/run/myscript.pid"

cleanup() {
  echo "I hate the kill command"
  rm -f "$filename"
  exit 0
}

trap 'cleanup' SIGQUIT SIGTERM
trap 'echo "Y U no love me?!"' SIGINT

echo $$ > "$filename"

while true; do
  echo "To infinity and beyond"
  sleep 1
done
