#!/usr/bin/env bash
# a bash script that displays the content of the file /etc/passwd
# the script displays username, user id, home dir path for user

file_path="/etc/passwd"
line=""

while read -r line 
do
	echo "$line" | cut -d ':' -f1,3,6
done < "$file_path"

