#!/usr/bin/env bash
# a script that displays the content content of the file
# /etc/passwd, using a while loop + IFS

file_path="/etc/passwd"
usrnme=""; pass=""; uid=""; gid=""; uidi=""; hme=""; cmd=""

while IFS=: read -r usrnme pass uid gid uidi hme cmd; do
	echo "The user $usrnme is part of the $gid gang,"\
	"lives in $hme and rides $cmd."\
	"$uid's place is protected by the passcode $pass,"\
	"more info about the user here: $uidi"
done < "$file_path"
