#!/usr/bin/env bash
# a script that displays "Best School" 10x but appends "Hi" on 9th

n=0
while [ "$n" -lt 10 ]; do
	if [ "$n" -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	n=$((n + 1))
done
