#!/usr/bin/env bash
# script that prints Best School on 10 iterations but diff for 4th and 8th

n=1

while [ "$n" -le 10 ]; do
	if [ "$n" -eq 4 ]; then
		echo "bad luck"
	elif [ "$n" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$((n + 1))
done
