#!/usr/bin/env bash
# a Bash script that displays the content of the current directory

for file in *; do
	if [[ ! "$file" =~ ^\. ]]; then
		name=$(echo "$file" | cut -d '-' -f 2-)

		echo "$name"
	fi
done
