#!/usr/bin/env bash
# script to install and setup ufw firewall on configure
# ssh,http and https connections

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
